spring:
  application:
    name: hello-world
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    schema:
      - classpath:schema.sql
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect